export const PHOTO_LIST_REQUEST = 'PHOTO_LIST_REQUEST';
export const PHOTO_LIST_SUCCESS = 'PHOTO_LIST_SUCCESS';
export const PHOTO_LIST_FAIL = 'PHOTO_LIST_FAIL';

export const PHOTO_DETAILS_REQUEST = 'PHOTO_DETAILS_REQUEST';
export const PHOTO_DETAILS_SUCCESS = 'PHOTO_DETAILS_SUCCESS';
export const PHOTO_DETAILS_FAIL = 'PHOTO_DETAILS_FAIL';

export const PHOTO_CREATE_REQUEST = 'PHOTO_CREATE_REQUEST';
export const PHOTO_CREATE_SUCCESS = 'PHOTO_CREATE_SUCCESS';
export const PHOTO_CREATE_FAIL = 'PHOTO_CREATE_FAIL';
export const PHOTO_CREATE_RESET = 'PHOTO_CREATE_RESET';

export const PHOTO_BY_USERID_REQUEST = 'PHOTO_BY_USERID_REQUEST';
export const PHOTO_BY_USERID_SUCCESS = 'PHOTO_BY_USERID_SUCCESS';
export const PHOTO_BY_USERID_FAIL = 'PHOTO_BY_USERID_FAIL';

export const PHOTO_FEED_REQUEST = 'PHOTO_FEED_REQUEST';
export const PHOTO_FEED_SUCCESS = 'PHOTO_FEED_SUCCESS';
export const PHOTO_FEED_FAIL = 'PHOTO_FEED_FAIL';

export const PHOTO_LIKE_REQUEST = 'PHOTO_LIKE_REQUEST';
export const PHOTO_LIKE_SUCCESS = 'PHOTO_LIKE_SUCCESS';
export const PHOTO_LIKE_FAIL = 'PHOTO_LIKE_FAIL';

export const PHOTO_COMMENT_REQUEST = 'PHOTO_COMMENT_REQUEST';
export const PHOTO_COMMENT_SUCCESS = 'PHOTO_COMMENT_SUCCESS';
export const PHOTO_COMMENT_FAIL = 'PHOTO_COMMENT_FAIL';
